name: Deploy

on:
  workflow_dispatch:
    inputs:
        target_env:
            type: environment
            description: Select the environment
        version:
            type: string
            description: Select version
  workflow_call:
    inputs:
        target_env:
            type: string
            required: true
        version:
            type: string
            required: true

jobs:
  pre-deploy-step:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: print environment
        run: | 
          echo "env selected is ${{ inputs.target_env }}"

      - name: print version
        run: |
          echo "version selected is ${{ inputs.version }}"
  
  deploy-step:
    runs-on: ubuntu-latest

    steps:
      - name: deploy image to server
        run: | 
          echo "Deploying image..."
          echo "Deploying image..."
          echo "Deploying image..."
          echo "Deployed successfully!"